// Everyday Chemistry — knowledge base bahan kimia pada label produk sehari-hari.
// Sengaja dipisah dari substances.ts: fokusnya istilah INCI + nama dagang Indonesia,
// bukan zat murni laboratorium. `formula` (jika ada) HARUS ada di SUBSTANCES.

export interface Ingredient {
  id: string;
  /** [nama utama (ID), ...alias INCI/nama dagang] */
  names: string[];
  /** Rumus kimia — hanya jika padanannya ada di database zat */
  formula?: string;
  /** Kelompok fungsi: Pengawet, Surfaktan, dst */
  group: string;
  /** Apa fungsinya di produk */
  role: string;
  /** Jenis produk yang biasanya memuatnya */
  foundIn: string[];
  /** Catatan keamanan singkat, jika perlu */
  safety?: string;
}

export const GROUPS = [
  "Pelarut & Basis",
  "Pelembap",
  "Surfaktan",
  "Pengawet",
  "Pengatur Keasaman",
  "Pemanis",
  "Perisa & Pewarna",
  "Nutrien",
  "Zat Aktif",
  "Pewarna Mineral",
  "Tekstur & Stabiliser",
  "Penambah Rasa",
  "Pemutih & Pembersih",
] as const;

export type Group = (typeof GROUPS)[number];

export const INGREDIENTS: Ingredient[] = [
  // ===== PELARUT & BASIS =====
  {
    id: "aqua",
    names: ["Aqua", "Air", "Water"],
    formula: "H2O",
    group: "Pelarut & Basis",
    role: "Pelarut utama — membawa semua bahan lain dan memberi bentuk cair produk.",
    foundIn: ["Hampir semua kosmetik & makanan cair"],
  },
  {
    id: "etanol",
    names: ["Etanol", "Ethanol", "Alcohol", "Alkohol"],
    formula: "C2H5OH",
    group: "Pelarut & Basis",
    role: "Pelarut bahan aktif sekaligus antiseptik; menguap cepat sehingga memberi sensasi dingin/kering.",
    foundIn: ["Hand sanitizer", "toner", "parfum", "obat kumur"],
    safety: "Konsentrasi tinggi bisa membuat kulit kering.",
  },
  {
    id: "aseton",
    names: ["Aseton", "Acetone", "Propanon"],
    formula: "CH3COCH3",
    group: "Pelarut & Basis",
    role: "Pelarut kuat — melarutkan cat kuku, lem, dan resin.",
    foundIn: ["Pembersih cat kuku", "thinner"],
    safety: "Mudah terbakar; keringkan kulit dan iritasi saluran napas.",
  },
  {
    id: "petrolatum",
    names: ["Petrolatum", "Vaselin", "Petroleum Jelly", "Parafin Padat"],
    group: "Pelarut & Basis",
    role: "Oklusif — membentuk lapisan pelindung yang menahan kelembapan kulit.",
    foundIn: ["Vaselin", "lip balm", "salep luka"],
  },
  // ===== PELEMBAP =====
  {
    id: "gliserin",
    names: ["Gliserin", "Glycerin", "Glycerol"],
    group: "Pelembap",
    role: "Humektan — menarik air ke permukaan kulit agar tetap lembap.",
    foundIn: ["Losion", "sabun mandi", "pasta gigi", "krim"],
  },
  {
    id: "sorbitol",
    names: ["Sorbitol", "E420"],
    group: "Pelembap",
    role: "Humektan dan pemanis rendah kalori; menjaga tekstur pasta gigi tetap lembap.",
    foundIn: ["Pasta gigi", "permen bebas gula", "sirup obat"],
    safety: "Berlebihan bisa bersifat laksatif ringan.",
  },
  {
    id: "pantenol",
    names: ["Pantenol", "Panthenol", "Pro-Vitamin B5", "Dexpanthenol"],
    group: "Pelembap",
    role: "Humektan + penenang — membantu regenerasi kulit dan meredakan iritasi ringan.",
    foundIn: ["Moisturizer", "hair vitamin", "losion bayi"],
  },
  {
    id: "gliserin-vegetali",
    names: ["Glyceryl Stearate", "Gliseril Stearat"],
    group: "Pelembap",
    role: "Emulgator & pelembap — mencampur air dan minyak agar tidak memisah.",
    foundIn: ["Krim wajah", "losion"],
  },
  // ===== SURFAKTAN =====
  {
    id: "sodium-laureth-sulfate",
    names: [
      "Sodium Laureth Sulfate",
      "SLES",
      "Natrium Lauret Sulfat",
      "Sodium Lauryl Ether Sulfate",
    ],
    group: "Surfaktan",
    role: "Penghasil busa utama — melekatkan air dan minyak agar kotoran terangkat saat dibilas.",
    foundIn: ["Sampo", "sabun cair", "pasta gigi", "sabun cuci piring"],
    safety: "Busanya banyak tapi bisa bikin kulit kering pada konsentrasi tinggi.",
  },
  {
    id: "sodium-lauryl-sulfate",
    names: ["Sodium Lauryl Sulfate", "SLS", "Natrium Lauril Sulfat"],
    group: "Surfaktan",
    role: "Surfaktan bersih keras — daya cuci tinggi, busa melimpah.",
    foundIn: ["Sabun cuci piring", "deterjen cair", "beberapa sampo"],
    safety: "Lebih iritasi daripada SLES; sering dihindari untuk kulit sensitif.",
  },
  {
    id: "cocamidopropyl-betaine",
    names: ["Cocamidopropyl Betaine", "Coco Betaine"],
    group: "Surfaktan",
    role: "Surfaktan lembut dari kelapa — melembutkan 'kesatan' SLES dan menstabilkan busa.",
    foundIn: ["Sampo", "sabun bayi", "facial wash"],
  },
  {
    id: "las-deterjen",
    names: [
      "Linear Alkylbenzene Sulfonate",
      "LAS",
      "Sodium Alkylbenzene Sulfonate",
      "Alkil Benzena Sulfonat",
    ],
    group: "Surfaktan",
    role: "Surfaktan utama deterjen bubuk/cair — mengangkat lemak dan kotoran dari kain.",
    foundIn: ["Deterjen bubuk", "deterjen cair"],
  },
  // ===== PENGAWET =====
  {
    id: "methylparaben",
    names: ["Methylparaben", "Nipagin", "Metilparaben"],
    group: "Pengawet",
    role: "Pengawet — mencegah jamur dan bakteri tumbuh di produk berbasis air.",
    foundIn: ["Kosmetik", "krim", "shampo"],
    safety: "Sudah lama dipakai dan dianggap aman pada kadar <0,4%; mitos 'bahaya' belum terbukti.",
  },
  {
    id: "propylparaben",
    names: ["Propylparaben", "Nipasol", "Propilparaben"],
    group: "Pengawet",
    role: "Pengawet pendamping methylparaben — lebih kuat melawan jamur.",
    foundIn: ["Kosmetik", "krim"],
    safety: "Batas penggunaan lebih ketat (maks 0,14%) karena aktivitas estrogennya sangat lemah.",
  },
  {
    id: "phenoxyethanol",
    names: ["Phenoxyethanol", "Fenoksietanol"],
    group: "Pengawet",
    role: "Pengawet modern pengganti paraben — efektif melawan bakteri gram-negatif.",
    foundIn: ["Sunscreen", "serum", "kosmetik 'paraben-free'"],
    safety: "Dibatasi maksimal 1% dalam kosmetik.",
  },
  {
    id: "natrium-benzoat",
    names: ["Sodium Benzoate", "Natrium Benzoat", "E211"],
    group: "Pengawet",
    role: "Pengawet makanan/minuman — efektif di suasana asam (minuman soda, jus).",
    foundIn: ["Minuman kemasan", "kecap", "saus", "selai"],
    safety: "Bereaksi dengan vitamin C membentuk benzena dalam jumlah sangat kecil (terkontrol BPOM).",
  },
  {
    id: "kalium-sorbat",
    names: ["Potassium Sorbate", "Kalium Sorbat", "E202"],
    group: "Pengawet",
    role: "Pengawet anti-jamur yang paling sering dipakai di roti dan keju.",
    foundIn: ["Roti", "keju", "yogurt drink", "saus"],
  },
  {
    id: "natrium-nitrit",
    names: ["Sodium Nitrite", "Natrium Nitrit", "E250"],
    group: "Pengawet",
    role: "Pengawet daging olahan — membunuh bakteri Clostridium botulinum dan memberi warna pink khas sosis.",
    foundIn: ["Sosis", "nugget", "ham", "daging asap"],
    safety: "Terlalu sering dikaitkan dengan risiko kesehatan — batasi konsumsi daging olahan.",
  },
  // ===== PENGATUR KEASAMAN =====
  {
    id: "asam-sitrat",
    names: ["Asam Sitrat", "Citric Acid", "E330"],
    group: "Pengatur Keasaman",
    role: "Pengasam alami dari jeruk — memberi rasa asam segar dan menstabilkan pH produk.",
    foundIn: ["Minuman", "permen", "facial wash", "deterjen"],
  },
  {
    id: "asam-laktat",
    names: ["Lactic Acid", "Asam Laktat", "E270"],
    group: "Pengatur Keasaman",
    role: "Pengatur pH hasil fermentasi; di kosmetik juga jadi exfoliant lembut (AHA).",
    foundIn: ["Yogurt", "roti", "peeling kulit"],
  },
  {
    id: "natrium-hidroksida",
    names: ["Sodium Hydroxide", "Natrium Hidroksida", "Soda Api", "Lye", "Kaustik Soda"],
    formula: "NaOH",
    group: "Pengatur Keasaman",
    role: "Basa kuat — dalam sabun menyabunkan minyak; dalam jumlah sedikit menetralkan pH produk.",
    foundIn: ["Sabun batang", "pembersih saluran pembuangan"],
    safety: "Padat/pekatkau korosif — hindari kontak kulit langsung.",
  },
  {
    id: "kalium-hidroksida",
    names: ["Potassium Hydroxide", "Kalium Hidroksida"],
    formula: "KOH",
    group: "Pengatur Keasaman",
    role: "Basa penyabun untuk sabun cair (soft soap); penyetel pH minor di kosmetik.",
    foundIn: ["Sabun cair", "sabun cukur"],
  },
  // ===== PEMANIS =====
  {
    id: "sukrosa",
    names: ["Sukrosa", "Sucrose", "Gula Pasir", "Gula"],
    formula: "C12H22O11",
    group: "Pemanis",
    role: "Pemanis utama dari tebu/bit — karbohidrat disakarida glukosa+fruktosa.",
    foundIn: ["Minuman manis", "kue", "hampir semua makanan olahan"],
  },
  {
    id: "glukosa",
    names: ["Glukosa", "Glucose", "Dextrose", "Dekstrosa"],
    formula: "C6H12O6",
    group: "Pemanis",
    role: "Gula sederhana — sumber energi langsung tubuh; sering dipakai sebagai sirup glukosa di permen.",
    foundIn: ["Permen", "minuman isotonik", "sirup"],
  },
  {
    id: "sirup-fruktosa",
    names: ["Fructose Syrup", "Sirup Fruktosa", "High Fructose Corn Syrup", "HFCS"],
    group: "Pemanis",
    role: "Pemanis murah dari jagung — lebih manis dari gula pasir.",
    foundIn: ["Soft drink impor", "sirup", "snack manis"],
    safety: "Asupan berlebih dikaitkan dengan obesitas dan resistensi insulin.",
  },
  {
    id: "sukralosa",
    names: ["Sucralose", "Sukralosa", "E955"],
    group: "Pemanis",
    role: "Pemanis buatan ~600× lebih manis dari gula, tanpa kalori.",
    foundIn: ["Minuman diet", "tabletop sweetener"],
  },
  {
    id: "aspartam",
    names: ["Aspartame", "Aspartam", "E951"],
    group: "Pemanis",
    role: "Pemanis buatan ~200× lebih manis dari gula.",
    foundIn: ["Minuman diet", "permen bebas gula"],
    safety: "Tidak boleh bagi penderita fenilketonuria (mengandung fenilalanin).",
  },
  {
    id: "natrium-sakarin",
    names: ["Sodium Saccharin", "Natrium Sakarin", "Sakarin", "E954"],
    group: "Pemanis",
    role: "Pemanis tertua (~300× gula) — masih dipakai di obat cair dan pasta gigi.",
    foundIn: ["Obat sirup", "pasta gigi", "pemanis meja"],
  },
  {
    id: "xilitol",
    names: ["Xylitol", "Xilitol", "E967"],
    group: "Pemanis",
    role: "Pemanis alami dari kayu birch — tidak memicu lubang gigi, malah anti-karies.",
    foundIn: ["Permen mint", "chewing gum bebas gula", "pasta gigi"],
    safety: "Sangat beracun untuk anjing.",
  },
  // ===== PERISA & PEWARNA =====
  {
    id: "parfum",
    names: ["Parfum", "Fragrance", "Aroma"],
    group: "Perisa & Pewarna",
    role: "Campuran puluhan molekul wangi — identitas aromanya rahasia dagang produsen.",
    foundIn: ["Hampir semua kosmetik", "deterjen", "softener"],
    safety: "Penyebab alergi kulit tersering di kosmetik.",
  },
  {
    id: "mentol",
    names: ["Menthol", "Mentol"],
    group: "Perisa & Pewarna",
    role: "Aktivator reseptor dingin kulit — sensasi sejuk tanpa menurunkan suhu.",
    foundIn: ["Pasta gigi", "obat gargle", "balsem", "permen mint"],
  },
  {
    id: "mononatrium-glutamat",
    names: ["Monosodium Glutamate", "Mononatrium Glutamat", "MSG", "Micin", "Vetsin", "E621"],
    group: "Penambah Rasa",
    role: "Pemberi rasa gurih (umami) — bentuk natrium dari asam amino glutamat.",
    foundIn: ["Mie instan", "kaldu blok", "snack", "masakan restoran"],
    safety: "Aman menurut JECFA/BPOM; stigma 'bahaya micin' tidak didukung bukti ilmiah.",
  },
  {
    id: "natrium-klorida",
    names: ["Sodium Chloride", "Natrium Klorida", "Garam Dapur", "Sea Salt"],
    formula: "NaCl",
    group: "Tekstur & Stabiliser",
    role: "Pengental murah di sampo & sabun cair; sekaligus pengatur viskositas.",
    foundIn: ["Sampo", "sabun cair", "pembersih wajah"],
    safety: "Kadar tinggi justru membuat produk surfaktannya kurang berbusa.",
  },
  {
    id: "karagenan",
    names: ["Carrageenan", "Karagenan", "E407"],
    group: "Tekstur & Stabiliser",
    role: "Pengental dari rumput laut merah — membuat tekstur susu/es krim lebih kental dan homogen.",
    foundIn: ["Es krim", "susu UHT cokelat", "jeli", "susu kedelai"],
  },
  {
    id: "pati-modifikasi",
    names: ["Modified Starch", "Pati Modifikasi", "Modified Corn Starch", "Pati Jagung"],
    group: "Tekstur & Stabiliser",
    role: "Pengental & stabilizer — bertahan panas/asam lebih baik dari pati biasa.",
    foundIn: ["Saus instan", "sup krim", "pudding", "snack"],
  },
  {
    id: "lesitin",
    names: ["Lecithin", "Lesitin", "Soja Lecithin", "E322"],
    group: "Tekstur & Stabiliser",
    role: "Emulgator dari kedelai — mencampur lemak dan air (misal di cokelat dan margarin).",
    foundIn: ["Cokelat", "margarin", "roti kemasan"],
  },
  {
    id: "maltodekstrin",
    names: ["Maltodextrin", "Maltodekstrin"],
    group: "Tekstur & Stabiliser",
    role: "Karbohidrat pendek — pengencer, pengikat rasa, dan pengisi volume bumbu instan.",
    foundIn: ["Bumbu sachet", "susu formula", "snack"],
  },
  // ===== NUTRIEN =====
  {
    id: "asam-askorbat",
    names: ["Ascorbic Acid", "Asam Askorbat", "Vitamin C", "E300"],
    formula: "C6H8O6",
    group: "Nutrien",
    role: "Vitamin C + antioksidan; di pangan juga mencegah pencoklatan buah.",
    foundIn: ["Jus", "suplemen", "skincare brightening"],
  },
  {
    id: "alfa-tokoferol",
    names: ["Tocopherol", "Alfa Tokoferol", "Vitamin E", "E306"],
    group: "Nutrien",
    role: "Antioksidan yang melindungi minyak dalam produk dari tengik; juga nutrisi kulit.",
    foundIn: ["Kosmetik", "minyak goreng", "suplemen"],
  },
  {
    id: "niacinamida",
    names: ["Niacinamide", "Niacinamida", "Nicotinamide", "Vitamin B3"],
    group: "Nutrien",
    role: "Multifungsi: meratakan warna kulit, memperkuat barrier, dan mengurangi produksi minyak.",
    foundIn: ["Serum", "moisturizer", "sunscreen"],
  },
  {
    id: "kafein",
    names: ["Caffeine", "Kafein"],
    formula: "C8H10N4O2",
    group: "Nutrien",
    role: "Stimulan alami — memblokir adenosin sehingga kantuk tertahan.",
    foundIn: ["Kopi", "teh", "energy drink", "eye cream"],
  },
  {
    id: "retinol",
    names: ["Retinol", "Vitamin A"],
    group: "Nutrien",
    role: "Emas anti-penuaan — mempercepat pergantian sel kulit dan merangsang kolagen.",
    foundIn: ["Night cream", "serum anti-aging"],
    safety: "Bikin kulit photosensitif — wajib pakai sunscreen pagi hari.",
  },
  {
    id: "kalsium-karbonat",
    names: ["Calcium Carbonate", "Kalsium Karbonat", "TPC", "Chalk"],
    formula: "CaCO3",
    group: "Nutrien",
    role: "Sumber kalsium + abrasif lembut pembersih di pasta gigi.",
    foundIn: ["Suplemen kalsium", "pasta gigi", "antasida"],
  },
  {
    id: "besi-terfortifikasi",
    names: ["Ferrous Fumarate", "Reduced Iron", "Besi Fortifikasi"],
    formula: "Fe",
    group: "Nutrien",
    role: "Fortifikasi zat besi — mencegah anemia pada tepung dan seral.",
    foundIn: ["Tepung terigu", "seral sarapan", "mie instan"],
  },
  // ===== ZAT AKTI =====
  {
    id: "asam-salisilat",
    names: ["Salicylic Acid", "Asam Salisilat", "BHA"],
    group: "Zat Aktif",
    role: "Exfoliant larut-minyak — masuk pori dan meluruhkan komedo; obat jerawat klasik.",
    foundIn: ["Facial wash jerawat", "toner", "spot treatment"],
    safety: "Batasi frekuensi — bisa membuat kulit kering/iritasi.",
  },
  {
    id: "benzoil-peroksida",
    names: ["Benzoyl Peroxide", "Benzoil Peroksida", "BPO"],
    group: "Zat Aktif",
    role: "Antibakteri jerawat — membunuh Cutibacterium acnes secara oksidatif.",
    foundIn: ["Krim jerawat", "facial wash acne"],
    safety: "Memutihkan kain dan rambut; mulai dari konsentrasi rendah (2,5%).",
  },
  {
    id: "urea",
    names: ["Urea"],
    group: "Zat Aktif",
    role: "Humektan + keratolitik — melembapkan sekaligus melunakkan kulit kasar/kaki pecah.",
    foundIn: ["Foot cream", "losion tubuh", "beberapa deodoran"],
  },
  {
    id: "hidrogen-peroksida",
    names: ["Hydrogen Peroxide", "Hidrogen Peroksida", "Air Oxiana"],
    formula: "H2O2",
    group: "Zat Aktif",
    role: "Antiseptic oksidator — mendesis saat menyentuh luka karena memecah oksigen.",
    foundIn: ["Antiseptik luka", "pemutih rambut", "pembersih telinga"],
    safety: "Kadar tinggi korosif; jangan campur dengan cuka dalam wadah tertutup.",
  },
  {
    id: "natrium-fluorida",
    names: ["Sodium Fluoride", "Natrium Fluorida"],
    group: "Zat Aktif",
    role: "Melapisi email gigi dengan fluorapatite — mencegah lubang gigi.",
    foundIn: ["Pasta gigi", "cekungan mulut (mouthwash)"],
  },
  {
    id: "aluminium-klorohidrat",
    names: ["Aluminum Chlorohydrate", "Aluminium Klorohidrat"],
    group: "Zat Aktif",
    role: "Antiperspirant — mengendapkan protein kelenjar keringat agar porinya menyempit sementara.",
    foundIn: ["Deodoran roll-on", "antiperspirant"],
    safety: "Mitos kaitan kanker payudara belum dibuktikan penelitian besar.",
  },
  {
    id: "karbon-aktif",
    names: ["Activated Charcoal", "Karbon Aktif", "Arang Aktif"],
    group: "Zat Aktif",
    role: "Adsorben — permukaan porousnya menyerapat racun, gas, dan pigmen.",
    foundIn: ["Masker wajah", "pemutih gigi", "obat keracunan"],
  },
  // ===== PEWARNA MINERAL =====
  {
    id: "titanium-dioksida",
    names: ["Titanium Dioxide", "Titanium Dioksida", "CI 77891"],
    group: "Pewarna Mineral",
    role: "Putih mineral — pewarna putih sekaligus filter UV fisik di sunscreen.",
    foundIn: ["Sunscreen", "bedak", "permen coating"],
  },
  {
    id: "zink-oksid",
    names: ["Zinc Oxide", "Seng Oksida", "CI 77947"],
    group: "Pewarna Mineral",
    role: "Filter UV lebar-spektrum + antiseptik kulit; tabir surya paling toleran untuk kulit sensitif.",
    foundIn: ["Sunscreen bayi", "diaper rash cream", "bedak"],
  },
  {
    id: "besi-oksida",
    names: ["Iron Oxides", "Besi Oksida", "CI 77491", "CI 77492"],
    formula: "Fe2O3",
    group: "Pewarna Mineral",
    role: "Pigmen kuning-merah-cokelat alami — penyesuai warna kulit di kosmetik.",
    foundIn: ["Foundation", "blush on", "lipstick"],
  },
  {
    id: "silika",
    names: ["Silica", "Silika", "Silycon Dioxide", "SiO2"],
    formula: "SiO2",
    group: "Pewarna Mineral",
    role: "Absorben minyak & anti-caking — membuat bedak tidak menggumpal.",
    foundIn: ["Bedak tabur", "primer", "obat nyamuk bakar"],
  },
  {
    id: "talk",
    names: ["Talc", "Talk", "Talkum", "Magnesium Silicate"],
    group: "Pewarna Mineral",
    role: "Menyerap keringat dan minyak, membuat kulit halus tak lengket.",
    foundIn: ["Bedak bayi", "bedak tabur", "deodoran bedak"],
    safety: "Pastikan produk bersertifikat — kontaminasi asbes pada talc murah adalah risikonya.",
  },
  {
    id: "dimetikon",
    names: ["Dimethicone", "Dimetikon", "Simethicone"],
    group: "Tekstur & Stabiliser",
    role: "Silikon — membentuk film halus di kulit/rambut ('slip'), tahan air.",
    foundIn: ["Primer makeup", "kondisioner", "krim anti-ruam"],
  },
  // ===== PEMUTIH & PEMBERSIH =====
  {
    id: "natrium-hipoklorit",
    names: ["Sodium Hypochlorite", "Natrium Hipoklorit", "Pemutih", "Bayclin"],
    formula: "NaClO",
    group: "Pemutih & Pembersih",
    role: "Pemutih oksidator — merusak pigmen dan membunuh hampir semua mikroorganisme.",
    foundIn: ["Pemutih pakaian", "pembersih lantai/toilet"],
    safety: "JANGAN dicampur cuka atau asam kamar mandi — menghasilkan gas klorin beracun.",
  },
  {
    id: "amonia",
    names: ["Ammonia", "Amonia", "Ammonium Hydroxide"],
    formula: "NH3",
    group: "Pemutih & Pembersih",
    role: "Basa volatile — memecah lemak dan kotoran kaca tanpa meninggalkan residu strip.",
    foundIn: ["Pembersih kaca", "pembersih lantai"],
    safety: "Uapnya menusuk mata; JANGAN pernah dicampur pemutih (gas kloramin).",
  },
  {
    id: "asam-klorida",
    names: ["Hydrochloric Acid", "Asam Klorida", "Spiritus Garam"],
    formula: "HCl",
    group: "Pemutih & Pembersih",
    role: "Asam kuat — melarutkan kerak urin dan karang di toilet.",
    foundIn: ["Pembersih kloset"],
    safety: "Korosif — selalu gunakan sarungan dan jangan hirup uapnya.",
  },
  {
    id: "asam-sulfat",
    names: ["Sulfuric Acid", "Asam Sulfat"],
    formula: "H2SO4",
    group: "Pemutih & Pembersih",
    role: "Asam sangat kuat — melunturkan sumbatan organik di saluran air.",
    foundIn: ["Drain cleaner"],
    safety: "Sangat berbahaya — reaksi hebat dengan air; serahkan ke profesional.",
  },
  {
    id: "asam-asetat",
    names: ["Acetic Acid", "Asam Asetat", "Cuka", "Vinegar"],
    formula: "CH3COOH",
    group: "Pemutih & Pembersih",
    role: "Asam lemah dapur — melarutkan kerak kapur dan menghilangkan bau.",
    foundIn: ["Cuka dapur", "pembersih rumah alami"],
  },
  {
    id: "natrium-bikarbonat",
    names: [
      "Sodium Bicarbonate",
      "Natrium Bikarbonat",
      "Baking Soda",
      "Soda Kue",
      "Sodium Hydrogen Carbonate",
    ],
    formula: "NaHCO3",
    group: "Pemutih & Pembersih",
    role: "Basa lemah serbaguna — pengembang kue, penghisap bau, abrasif lembut pembersih.",
    foundIn: ["Soda kue", "pasta gigi", "pembersih ramah lingkungan"],
  },
  {
    id: "natrium-tripolifosfat",
    names: ["Sodium Tripolyphosphate", "Natrium Tripolifosfat", "STPP", "E451"],
    group: "Pemutih & Pembersih",
    role: "Builder deterjen — mengikat ion Ca/Mg agar air lunak dan deterjen bekerja optimal.",
    foundIn: ["Deterjen bubuk", "sosis (penahan air)"],
    safety: "Versi limbahnya jadi pemicu eutrofikasi sungai/danau.",
  },
  {
    id: "natrium-perkarbonat",
    names: ["Sodium Percarbonate", "Natrium Perkarbonat", "Oxi-type bleach"],
    group: "Pemutih & Pembersih",
    role: "Pemutih oksigen — di air melepas hidrogen peroksida, lebih ramah lingkungan dari pemutih klorin.",
    foundIn: ["Vanish/OxiClean", "deterjen anti-noda"],
  },
];
