// Kuis mini per fenomena — 2-3 soal pilihan ganda dengan pembahasan singkat.
// PENTING: panjang opsi dibuat seragam agar tidak membocorkan jawaban.

export interface QuizQuestion {
  q: string;
  options: string[];
  answer: number; // index
  explain: string;
}

export const QUIZZES: Record<string, QuizQuestion[]> = {
  "besi-berkarat": [
    {
      q: "Zat apa saja yang dibutuhkan agar besi berkarat?",
      options: ["Oksigen dan air hujan",
          "Air dan cahaya",
          "Garam dan udara",
          "Karbon dioksida"],
      answer: 0,
      explain: "Karat butuh O₂ DAN H₂O sekaligus — besi di gurun kering atau dalam air bebas udara jauh lebih awet.",
    },
    {
      q: "Dalam reaksi korosi, besi mengalami…",
      options: ["Netralisasi",
          "Pengendapan",
          "Oksidasi (teroksidasi)",
          "Reduksi (tereduksi)"],
      answer: 2,
      explain: "Fe → Fe²⁺ + 2e⁻. Besi melepas elektron, artinya teroksidasi. Oksigen-lah yang menerimanya.",
    },
  ],
  "minyak-air": [
    {
      q: "Mengapa minyak dan air tidak dapat bercampur?",
      options: ["Ada reaksi yang menghalangi",
          "Bedanya polaritas molekul",
          "Air memiliki tegangan permukaan tinggi",
          "Minyak bermassa jenis lebih kecil"],
      answer: 1,
      explain: "Prinsip 'serupa melarutkan serupa': air polar menolak minyak nonpolar karena mencampur keduanya tidak menguntungkan secara energi.",
    },
    {
      q: "Senyawa apa yang membuat campuran minyak dan air stabil?",
      options: ["Cuka meja",
          "Garam dapur (NaCl)",
          "Gula pasir",
          "Emulgator (lesitin"],
      answer: 3,
      explain: "Emulgator punya kepala suka air dan ekor suka minyak — menjembatani keduanya. Itulah rahasia mayones.",
    },
  ],
  "telur-dipanaskan": [
    {
      q: "Proses rusaknya lipatan protein telur akibat panas disebut…",
      options: ["Denaturasi protein",
          "Fermentasi asam",
          "Hidrolisis enzim",
          "Koagulasi koloid"],
      answer: 0,
      explain: "Panas merusak lipatan protein = denaturasi. Untaian yang terurai lalu saling menaut = koagulasi (langkah berikutnya).",
    },
    {
      q: "Bisakah telur matang kembali cair jika didinginkan?",
      options: ["Hanya putihnya yang bisa",
          "Ya, jika cepat didinginkan",
          "Tidak, perubahan itu",
          "Ya, jika direbus ulang"],
      answer: 2,
      explain: "Denaturasi oleh panas ireversibel — ikatan baru yang terbentuk berbeda dari semula. Beda dengan mayones yang reversibel.",
    },
  ],
  "apel-menghitam": [
    {
      q: "Gas apa yang bereaksi dengan zat dalam apel hingga menghitam?",
      options: ["Karbondioksida",
          "Oksigen dari udara luar",
          "Nitrogen",
          "Uap air"],
      answer: 1,
      explain: "Enzim polifenol oksidase memakai O₂ untuk mengubah polifenol menjadi kuinon lalu melanin cokelat.",
    },
    {
      q: "Bagaimana cara kerja jeruk nipis mencegah pencoklatan?",
      options: ["Melapisi permukaan dengan lilin",
          "Membunuh semua sel buah",
          "Menambah warna cerah pada daging buah",
          "Menurunkan pH & vitamin C menjadi"],
      answer: 3,
      explain: "Dua efek sekaligus: pH rendah memperlambat enzim, vitamin C teroksidasi duluan 'mengorbankan diri'.",
    },
  ],
  "api-menyala": [
    {
      q: "Apa penyebab api dapat menjalar dengan sendirinya?",
      options: ["Panas reaksi merambat sendiri",
          "Angin membarkan bara ke kayu lain",
          "Kayu mengandung minyak alami",
          "Oksigen tertarik oleh nyala"],
      answer: 0,
      explain: "Reaksi eksotermik melepas panas yang cukup untuk menyalakan bahan di sekitarnya — reaksi berantai yang menopang diri sendiri.",
    },
    {
      q: "Cara utama air memadamkan api adalah…",
      options: ["Mengencerkan bahan bakar",
          "Menutup rapat sumber oksigen",
          "Menyerap panas saat menguap",
          "Mereaksikan diri dengan nyala api"],
      answer: 2,
      explain: "Penguapan air menyerap banyak energi sehingga suhu turun di bawah titik nyala — segitiga api rusak di sisi panas.",
    },
  ],
  fotosintesis: [
    {
      q: "Sumber utama massa tubuh pohon yang raksasa adalah…",
      options: ["Air yang diserap daun",
          "CO₂ dari udara",
          "Mineral tanah via akar",
          "Pupuk organik"],
      answer: 1,
      explain: "Atom karbon tubuh tumbuhan datang dari CO₂ lewat fotosintesis — eksperimen willow Van Helmont membuktikannya abad ke-17.",
    },
    {
      q: "Produk samping fotosintesis yang penting bagi hidup kita adalah…",
      options: ["Glukosa sebagai cadangan",
          "Karbondioksida sisa",
          "Uap air transpirasi",
          "Oksigen hasil fotolisis"],
      answer: 3,
      explain: "O₂ dilepas saat molekul air dipecah di fotosistem II — tanpa itu atmosfer bumi tak beroksigen.",
    },
  ],
  "pernapasan-sel": [
    {
      q: "Ke mana energi kimia nasi sebagian besar berakhir di tubuh?",
      options: ["Tertampung dalam molekul ATP",
          "Berubah menjadi otot",
          "Disimpan sebagai glukosa darah",
          "Keluar sebagai keringat"],
      answer: 0,
      explain: "Respirasi seluler menampung energi ke ikatan fosfat ATP (±30 ATP per glukosa) — mata uang energi semua sel.",
    },
    {
      q: "Kenapa pembakaran biologis tidak menghasilkan nyala seperti api?",
      options: ["Enzim memadamkan nyala",
          "Suhu tubuh terlalu rendah untuk menyala",
          "Energi ditransfer bertahap ke ATP",
          "Tidak ada oksigen di dalam sel"],
      answer: 2,
      explain: "Okidasi di mitokondria berlangsung bertahap lewat rantai transpor elektron; energinya ditampung, bukan dilepas sekaligus.",
    },
  ],
  "garam-mencairkan-es": [
    {
      q: "Mekanisme garam melelehkan es adalah…",
      options: ["Menaikkan suhu lingkungan",
          "Mengacaukan susunan kristalnya",
          "Menyerap es ke dalam garam",
          "Mereaksikan es menjadi air"],
      answer: 1,
      explain: "Ion Na⁺/Cl⁻ mengacaukan kristal es yang sedang terbentuk — depresi titik beku, sifat koligatif larutan.",
    },
    {
      q: "Pada −25°C, apakah garam dapur masih efektif mencairkan es?",
      options: ["Hanya jika dicampur pasir",
          "Ya, bekerja di suhu berapa pun",
          "Ya, tapi butuh dosis ganda",
          "Tidak — batas NaCl sekitar"],
      answer: 3,
      explain: "Titik eutektik NaCl ≈ −21°C. Di bawahnya larutan jenuh membeku juga; untuk ekstrem dipakai CaCl₂.",
    },
  ],
  "soda-berbusa": [
    {
      q: "Asal gelembung soda adalah…",
      options: ["CO₂ yang dipaksa larut",
          "Aktivitas bakteri manisan",
          "Reaksi dengan gelas kaca",
          "Udara yang masuk saat dituang"],
      answer: 0,
      explain: "Hukum Henry: kelarutan gas sebanding tekanannya. Saat botol dibuka tekanan jatuh dan CO₂ keluar dari larutan.",
    },
    {
      q: "Mengapa soda hangat lebih cepat kehilangan gelembungnya?",
      options: ["CO₂ bereaksi dengan gula",
          "Gelembung pecah oleh panas",
          "Kelarutan gas turun saat",
          "Tekanan dalam botol naik"],
      answer: 2,
      explain: "Molekul gas makin lincah saat hangat dan mudah lolos — kelarutan gas berbanding terbalik dengan suhu.",
    },
  ],
  "baking-soda-cuka": [
    {
      q: "Gas yang dihasilkan reaksi baking soda dengan cuka adalah…",
      options: ["Hidrogen",
          "Karbondioksida",
          "Oksigen murni",
          "Uap ammonia"],
      answer: 1,
      explain: "HCO₃⁻ + asam → CO₂ + H₂O + garam. Busa yang terlihat adalah ribuan gelembung CO₂ hasil netralisasi.",
    },
    {
      q: "Prinsip reaksi soda-cuka dimanfaatkan dalam pembuatan kue melalui…",
      options: ["Cuka melunakkan tekstur tepung",
          "Garam mengawetkan adonan",
          "Netralisasi menghilangkan rasa",
          "CO₂ baking soda mengembangkan"],
      answer: 3,
      explain: "CO₂ terperangkap jala gluten mengembang saat dipanggang — mekanisme persis sama dengan gunung berapi mini.",
    },
  ],
  "sabun-mencuci": [
    {
      q: "Bagian molekul sabun yang menusuk ke dalam lemak adalah…",
      options: ["Ekor yang suka",
          "Ikatan tengahnya",
          "Kepala yang suka air",
          "Muatan negatifnya"],
      answer: 0,
      explain: "Ekor hidrofobik menusuk lemak (nonpolar), kepala hidrofilik menghadap air — membentuk misel yang bisa dibilas.",
    },
    {
      q: "Selain mengangkat lemak, efek sabun lain pada air adalah…",
      options: ["Membunuh mineralnya",
          "Mengubah warnanya",
          "Menurunkan tegangan permukaan",
          "Meningkatkan titik didihnya"],
      answer: 2,
      explain: "Surfaktan merusak tegangan permukaan sehingga air merambat masuk celah kain dan melepaskan selubung lemak virus.",
    },
  ],
  yoghurt: [
    {
      q: "Perubahan susu menjadi yoghurt terjadi karena…",
      options: ["Pemanasan suhu tinggi lama",
          "Fermentasi laktosa oleh",
          "Penambahan enzim papaya",
          "Pendinginan suhu ruang"],
      answer: 1,
      explain: "Lactobacillus mengubah laktosa menjadi asam laktat; pH turun sampai kasein menggumpal menjadi tekstur kental.",
    },
    {
      q: "Alasan yoghurt lebih awet daripada susu segar adalah…",
      options: ["Kandungan airnya lebih rendah",
          "Laktosanya telah hilang",
          "Sudah bebas bakteri total",
          "Asam menghambat bakteri"],
      answer: 3,
      explain: "pH ~4,5 tak nyaman bagi mikroba pembusuk — fermentasi adalah teknologi pengawetan tertua dunia.",
    },
  ],
  "minyak-tengik": [
    {
      q: "Penyebab utama minyak goreng menjadi tengik adalah…",
      options: ["Serangan oksigen pada ikatan",
          "Penguapan asam lemaknya",
          "Penguapan molekul aromanya",
          "Pertumbuhan jamur mikroskopis"],
      answer: 0,
      explain: "Auto-oksidasi: radikal bebas menyerang ikatan rangkap asam lemak tak jenuh, menghasilkan aldehida/keton bau tengik.",
    },
    {
      q: "Kondisi penyimpanan yang PALING mempercepat minyak tengik adalah…",
      options: ["Dingin di dalam kulkas",
          "Tempat gelap dan tertutup",
          "Terang, panas, dekat",
          "Wadah kaca tertutup"],
      answer: 2,
      explain: "Cahaya memicu radikal, panas mempercepat reaksi, logam jadi katalis — kombinasi ketiganya adalah resep tengik kilat.",
    },
  ],
  "perak-menghitam": [
    {
      q: "Unsur yang bereaksi dengan perak hingga menghitam adalah…",
      options: ["Karbon dioksida",
          "Sulfur dari polusi udara",
          "Nitrogen udara",
          "Oksigen dari udara"],
      answer: 1,
      explain: "Ag + H₂S → Ag₂S hitam. Telur kaya sulfur — makanya sendok perak cepat hitam dipakai makan telur.",
    },
    {
      q: "Cara aluminium foil + air garam membersihkan perak bekerja dengan…",
      options: ["Melarutkan perak sulfida",
          "Memutihkan oleh elektrolit",
          "Mengerik lapisan hitamnya",
          "Aluminium mengambil"],
      answer: 3,
      explain: "Al lebih reaktif: teroksidasi menggantikan Ag dalam Ag₂S — perak kembali metalik tanpa digosok.",
    },
  ],
  "patung-perunggu-hijau": [
    {
      q: "Warna hijau patung tembaga tua berasal dari senyawa…",
      options: ["Karbonat tembaga",
          "Klorida tembaga putih",
          "Tembaga oksida hitam",
          "Tembaga sulfat biru"],
      answer: 0,
      explain: "Cu bereaksi dengan O₂, CO₂, dan air hujan membentuk Cu₂(OH)₂CO₃ hijau — patina yang justru melindungi logam.",
    },
    {
      q: "Perbedaan penting karat besi dengan patina tembaga adalah…",
      options: ["Karat hanya muncul di laut",
          "Patina lebih cepat terbentuk",
          "Patina melindungi logam di",
          "Patina mudah terkelupas"],
      answer: 2,
      explain: "Patina rapat dan melekat kuat — lapisan barier yang meregenerasi sendiri. Karat besi berpori sehingga korosi menembus terus.",
    },
  ],
  "bau-keringat": [
    {
      q: "Sebenarnya bau kaki berasal dari…",
      options: ["Debu yang menempel kulit",
          "Hasil metabolisme bakteri",
          "Keringat itu sendiri",
          "Material sepatu yang terurai"],
      answer: 1,
      explain: "Keringat segar tak berbau. Bakteri mencernanya dan membuang asam isovalerat/propionat — inilah yang kita cium.",
    },
    {
      q: "Strategi paling efektif mengurangi bau kaki adalah…",
      options: ["Mandi dengan air panas tiap jam",
          "Memakai dua pasang kaos kaki",
          "Menggosok kaki dengan alkohol",
          "Memutus kelembapan habitat"],
      answer: 3,
      explain: "Bakteri butuh lingkungan hangat-lembap. Kaus katun dan sepatu kering mengubah habitatnya — lebih tahan lama daripada sekadar membunuh.",
    },
  ],
  "pemutih-pakaian": [
    {
      q: "Cara pemutih menghilangkan warna noda adalah…",
      options: ["Merusak bagian molekul",
          "Melarutkan seluruh molekul noda",
          "Mencuci noda keluar dari serat",
          "Menutupi noda dengan putihan"],
      answer: 0,
      explain: "Hipoklorit mengoksidasi kromofor (bagian penyerap cahaya) — molekul noda tetap ada tapi tak lagi berwarna.",
    },
    {
      q: "Mengapa pemutih tidak boleh dicampur cuka?",
      options: ["Menetralkan efek pemutih",
          "Menghasilkan ledakan kecil",
          "Melepaskan gas klorin",
          "Merusak serat pakaian"],
      answer: 2,
      explain: "OCl⁻ + Cl⁻ + 2H⁺ → Cl₂ gas. Klorin sangat beracun — fatal di ruangan tertutup meski volumenya kecil.",
    },
  ],
  "kunang-kunang": [
    {
      q: "Sumber cahaya bioluminesensi kunang-kunang adalah reaksi…",
      options: ["Fosfor yang menyala di udara",
          "Luciferin + oksigen oleh",
          "Listrik statis tubuhnya",
          "Refleksi cahaya bulan"],
      answer: 1,
      explain: "Luciferase menggabungkan luciferin dengan O₂ (ditenagai ATP) — molekul berenergi tinggi melepas foton saat tenang kembali.",
    },
    {
      q: "Yang membuat cahaya kunang-kunang istimewa dibanding bohlam pijar adalah…",
      options: ["Cahayanya lebih terang",
          "Tidak membutuhkan energi",
          "Warnanya yang bisa berubah-ubah",
          "Efisiensi: hampir tanpa panas"],
      answer: 3,
      explain: "Hampir semua energi reaksi jadi cahaya; bohlam pijar sebaliknya — 90% energi terbuang jadi panas.",
    },
  ],
  "kerak-ketel": [
    {
      q: "Komposisi kerak putih di dasar ketel adalah…",
      options: ["Kalsium karbonat endapan",
          "Garam dapur yang mengkristal",
          "Oksida logam ketel",
          "Silika dari air hujan"],
      answer: 0,
      explain: "Kalsium bikarbonat terlarut terurai saat dipanaskan menjadi CaCO₃ tak larut — mengendap sebagai kerak keras.",
    },
    {
      q: "Cuka membersihkan kerak melalui cara…",
      options: ["Membakarnya hingga luruh",
          "Membunuh mineral penyusunnya",
          "Melarutkannya sebagai garam",
          "Mengeras-kannya lalu terkelupas"],
      answer: 2,
      explain: "CaCO₃ + 2CH₃COOH → kalsium asetat (larut) + H₂O + CO₂↑ — desisnya adalah bukti reaksi berlangsung.",
    },
  ],
  "roti-mengembang": [
    {
      q: "Gas penyebab roti mengembang berasal dari…",
      options: ["Reaksi baking powder",
          "Fermentasi gula oleh ragi",
          "Uap air oven yang masuk adonan",
          "Udara yang dikocok saat diulat"],
      answer: 1,
      explain: "Ragi mencerna gula → etanol + CO₂. Gelembung CO₂ terjebak jala gluten membuat roti berongga ringan.",
    },
    {
      q: "Protein tepung yang membentuk jala elastis penahan gas bernama…",
      options: ["Albumin",
          "Amilopektin",
          "Kasein",
          "Gluten"],
      answer: 3,
      explain: "Gluten (gliadin+glutenin) elastis menahan gelembung gas — makanya tepung beras (tanpa gluten) tak bisa bikin roti mengembang.",
    },
  ],
  "hortensia-warna": [
    {
      q: "Faktor penentu warna biru vs merah muda bunga hortensia adalah…",
      options: ["Keasaman tanah &",
          "Jenis pupuk organiknya",
          "Jumlah sinar matahari",
          "Usia bunga tersebut"],
      answer: 0,
      explain: "Tanah asam melarutkan Al³⁺ yang terserap bunga → kompleks pigmen biru. Tanah basa mengunci aluminium → merah muda.",
    },
    {
      q: "Kelompok pigmen yang warnanya sensitif terhadap pH pada hortensia adalah…",
      options: ["Betalaian",
          "Karotenoid",
          "Antosianin",
          "Klorofil"],
      answer: 2,
      explain: "Antosianin juga pewarna blueberry & kubis ungu — sensornya terhadap pH sama seperti indikator lakmus.",
    },
  ],
  "pelangi-genangan": [
    {
      q: "Pelangi warna di genangan bensin muncul karena…",
      options: ["Pemantulan warna mobil lewat",
          "Interferensi cahaya pada film",
          "Reaksi oli dengan aspal basah",
          "Spektrum cahaya dari langit senja"],
      answer: 1,
      explain: "Pantulan dari permukaan atas & bawah film oli saling menguatkan/melemahkan tiap panjang gelombang — warna bergantung ketebalan film.",
    },
    {
      q: "Fenomena lain yang bekerja dengan prinsip sama adalah…",
      options: ["Kilau permata berlian",
          "Warna langit siang hari",
          "Warna pelangi setelah hujan",
          "Warna-warni gelembung"],
      answer: 3,
      explain: "Film sabun juga tipis dan bervariasi ketebalannya — kontur warnanya adalah peta ketebalan film secara real-time.",
    },
  ],
  "embun-pagi": [
    {
      q: "Embun pagi berasal dari…",
      options: ["Uap air udara yang",
          "Air tanah yang meresap naik",
          "Hujan halus semalaman",
          "Rembesan dari atap"],
      answer: 0,
      explain: "Permukaan dingin (rumput/atap) jatuh di bawah titik embun — uap di sekitarnya berkondensasi jadi titik air.",
    },
    {
      q: "Syarat terbentuknya embun pada permukaan adalah suhu permukaan…",
      options: ["Lebih tinggi dari suhu udara",
          "Sama dengan suhu udara",
          "Lebih rendah dari titik",
          "Tepat nol derajat Celsius"],
      answer: 2,
      explain: "Di bawah titik embun, udara di dekat permukaan jenuh — uap tak lagi bisa 'tersembunyi' dan menjadi cairan.",
    },
  ],
};
